version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightning-hydra-template:latest
    container_name: lightning-hydra-dev
    
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Environment variables
    environment:
      - PYTHONPATH=/workspace
      - WANDB_API_KEY=${WANDB_API_KEY}
      - CUDA_VISIBLE_DEVICES=0
    
    # Volumes
    volumes:
      - .:/workspace
      - ~/.cache:/root/.cache
      - ~/.ssh:/root/.ssh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
    # Network mode for X11 forwarding
    network_mode: host
    
    # IPC mode for shared memory
    ipc: host
    
    # Security options
    security_opt:
      - seccomp:unconfined
    
    # Resource limits
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Ports
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
      - "4040:4040"  # Spark UI (if needed)
    
    command: /bin/bash

  # Optional: TensorBoard service
  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightning-hydra-template:latest
    container_name: lightning-hydra-tensorboard
    
    volumes:
      - ./logs:/workspace/logs:ro
    
    ports:
      - "6007:6007"
    
    command: tensorboard --logdir=/workspace/logs --host=0.0.0.0 --port=6007

  # Optional: Jupyter service
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightning-hydra-template:latest
    container_name: lightning-hydra-jupyter
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    volumes:
      - .:/workspace
      - ~/.cache:/root/.cache
    
    ports:
      - "8889:8888"
    
    environment:
      - PYTHONPATH=/workspace
    
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root