# Enhanced W&B logging with additional metrics and artifacts

defaults:
  - wandb.yaml

# Additional callbacks for enhanced logging
callbacks:
  wandb_enhanced:
    _target_: src.utils.logging_callbacks.WandbEnhancedLogger
    log_gradients: true
    log_model_architecture: true
    log_best_model: true
    watch_model: true
  
  # Local metrics logging for CLI tools
  metrics_logger:
    _target_: src.utils.logging_callbacks.MetricsLogger
    save_json: true
    save_csv: true
    log_grad_norm: true
    log_lr: true
    log_epoch_time: true
  
  checkpoint_metrics:
    _target_: src.utils.logging_callbacks.CheckpointMetricsLogger